provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  timezone-shift:
    lang: node
    handler: ./timezone-shift
    image: timezone-shift:latest-0.5
    labels:
      com.openfaas.scale.zero: false
